/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jp.co.liferay.reservation.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import jp.co.liferay.reservation.model.PersistedPurpose;
import jp.co.liferay.reservation.service.PersistedPurposeLocalService;
import jp.co.liferay.reservation.service.persistence.PersistedAmenityPersistence;
import jp.co.liferay.reservation.service.persistence.PersistedBookingPersistence;
import jp.co.liferay.reservation.service.persistence.PersistedOfficePersistence;
import jp.co.liferay.reservation.service.persistence.PersistedParticipantPersistence;
import jp.co.liferay.reservation.service.persistence.PersistedPurposePersistence;
import jp.co.liferay.reservation.service.persistence.PersistedRoomPersistence;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the persisted purpose local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link jp.co.liferay.reservation.service.impl.PersistedPurposeLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see jp.co.liferay.reservation.service.impl.PersistedPurposeLocalServiceImpl
 * @generated
 */
public abstract class PersistedPurposeLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   PersistedPurposeLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>PersistedPurposeLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>jp.co.liferay.reservation.service.PersistedPurposeLocalServiceUtil</code>.
	 */

	/**
	 * Adds the persisted purpose to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedPurposeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param persistedPurpose the persisted purpose
	 * @return the persisted purpose that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PersistedPurpose addPersistedPurpose(
		PersistedPurpose persistedPurpose) {

		persistedPurpose.setNew(true);

		return persistedPurposePersistence.update(persistedPurpose);
	}

	/**
	 * Creates a new persisted purpose with the primary key. Does not add the persisted purpose to the database.
	 *
	 * @param purposeId the primary key for the new persisted purpose
	 * @return the new persisted purpose
	 */
	@Override
	@Transactional(enabled = false)
	public PersistedPurpose createPersistedPurpose(long purposeId) {
		return persistedPurposePersistence.create(purposeId);
	}

	/**
	 * Deletes the persisted purpose with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedPurposeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param purposeId the primary key of the persisted purpose
	 * @return the persisted purpose that was removed
	 * @throws PortalException if a persisted purpose with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PersistedPurpose deletePersistedPurpose(long purposeId)
		throws PortalException {

		return persistedPurposePersistence.remove(purposeId);
	}

	/**
	 * Deletes the persisted purpose from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedPurposeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param persistedPurpose the persisted purpose
	 * @return the persisted purpose that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PersistedPurpose deletePersistedPurpose(
		PersistedPurpose persistedPurpose) {

		return persistedPurposePersistence.remove(persistedPurpose);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			PersistedPurpose.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return persistedPurposePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jp.co.liferay.reservation.model.impl.PersistedPurposeModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return persistedPurposePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jp.co.liferay.reservation.model.impl.PersistedPurposeModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return persistedPurposePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return persistedPurposePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return persistedPurposePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public PersistedPurpose fetchPersistedPurpose(long purposeId) {
		return persistedPurposePersistence.fetchByPrimaryKey(purposeId);
	}

	/**
	 * Returns the persisted purpose with the matching UUID and company.
	 *
	 * @param uuid the persisted purpose's UUID
	 * @param companyId the primary key of the company
	 * @return the matching persisted purpose, or <code>null</code> if a matching persisted purpose could not be found
	 */
	@Override
	public PersistedPurpose fetchPersistedPurposeByUuidAndCompanyId(
		String uuid, long companyId) {

		return persistedPurposePersistence.fetchByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns the persisted purpose with the matching external reference code and company.
	 *
	 * @param companyId the primary key of the company
	 * @param externalReferenceCode the persisted purpose's external reference code
	 * @return the matching persisted purpose, or <code>null</code> if a matching persisted purpose could not be found
	 */
	@Override
	public PersistedPurpose fetchPersistedPurposeByReferenceCode(
		long companyId, String externalReferenceCode) {

		return persistedPurposePersistence.fetchByC_ERC(
			companyId, externalReferenceCode);
	}

	/**
	 * Returns the persisted purpose with the primary key.
	 *
	 * @param purposeId the primary key of the persisted purpose
	 * @return the persisted purpose
	 * @throws PortalException if a persisted purpose with the primary key could not be found
	 */
	@Override
	public PersistedPurpose getPersistedPurpose(long purposeId)
		throws PortalException {

		return persistedPurposePersistence.findByPrimaryKey(purposeId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			persistedPurposeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PersistedPurpose.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("purposeId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			persistedPurposeLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(PersistedPurpose.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("purposeId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			persistedPurposeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PersistedPurpose.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("purposeId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return persistedPurposeLocalService.deletePersistedPurpose(
			(PersistedPurpose)persistedModel);
	}

	public BasePersistence<PersistedPurpose> getBasePersistence() {
		return persistedPurposePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return persistedPurposePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the persisted purpose with the matching UUID and company.
	 *
	 * @param uuid the persisted purpose's UUID
	 * @param companyId the primary key of the company
	 * @return the matching persisted purpose
	 * @throws PortalException if a matching persisted purpose could not be found
	 */
	@Override
	public PersistedPurpose getPersistedPurposeByUuidAndCompanyId(
			String uuid, long companyId)
		throws PortalException {

		return persistedPurposePersistence.findByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns a range of all the persisted purposes.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jp.co.liferay.reservation.model.impl.PersistedPurposeModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of persisted purposes
	 * @param end the upper bound of the range of persisted purposes (not inclusive)
	 * @return the range of persisted purposes
	 */
	@Override
	public List<PersistedPurpose> getPersistedPurposes(int start, int end) {
		return persistedPurposePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of persisted purposes.
	 *
	 * @return the number of persisted purposes
	 */
	@Override
	public int getPersistedPurposesCount() {
		return persistedPurposePersistence.countAll();
	}

	/**
	 * Updates the persisted purpose in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedPurposeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param persistedPurpose the persisted purpose
	 * @return the persisted purpose that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PersistedPurpose updatePersistedPurpose(
		PersistedPurpose persistedPurpose) {

		return persistedPurposePersistence.update(persistedPurpose);
	}

	/**
	 */
	@Override
	public void addPersistedRoomPersistedPurpose(long roomId, long purposeId) {
		persistedRoomPersistence.addPersistedPurpose(roomId, purposeId);
	}

	/**
	 */
	@Override
	public void addPersistedRoomPersistedPurpose(
		long roomId, PersistedPurpose persistedPurpose) {

		persistedRoomPersistence.addPersistedPurpose(roomId, persistedPurpose);
	}

	/**
	 */
	@Override
	public void addPersistedRoomPersistedPurposes(
		long roomId, long[] purposeIds) {

		persistedRoomPersistence.addPersistedPurposes(roomId, purposeIds);
	}

	/**
	 */
	@Override
	public void addPersistedRoomPersistedPurposes(
		long roomId, List<PersistedPurpose> persistedPurposes) {

		persistedRoomPersistence.addPersistedPurposes(
			roomId, persistedPurposes);
	}

	/**
	 */
	@Override
	public void clearPersistedRoomPersistedPurposes(long roomId) {
		persistedRoomPersistence.clearPersistedPurposes(roomId);
	}

	/**
	 */
	@Override
	public void deletePersistedRoomPersistedPurpose(
		long roomId, long purposeId) {

		persistedRoomPersistence.removePersistedPurpose(roomId, purposeId);
	}

	/**
	 */
	@Override
	public void deletePersistedRoomPersistedPurpose(
		long roomId, PersistedPurpose persistedPurpose) {

		persistedRoomPersistence.removePersistedPurpose(
			roomId, persistedPurpose);
	}

	/**
	 */
	@Override
	public void deletePersistedRoomPersistedPurposes(
		long roomId, long[] purposeIds) {

		persistedRoomPersistence.removePersistedPurposes(roomId, purposeIds);
	}

	/**
	 */
	@Override
	public void deletePersistedRoomPersistedPurposes(
		long roomId, List<PersistedPurpose> persistedPurposes) {

		persistedRoomPersistence.removePersistedPurposes(
			roomId, persistedPurposes);
	}

	/**
	 * Returns the roomIds of the persisted rooms associated with the persisted purpose.
	 *
	 * @param purposeId the purposeId of the persisted purpose
	 * @return long[] the roomIds of persisted rooms associated with the persisted purpose
	 */
	@Override
	public long[] getPersistedRoomPrimaryKeys(long purposeId) {
		return persistedPurposePersistence.getPersistedRoomPrimaryKeys(
			purposeId);
	}

	/**
	 */
	@Override
	public List<PersistedPurpose> getPersistedRoomPersistedPurposes(
		long roomId) {

		return persistedPurposePersistence.getPersistedRoomPersistedPurposes(
			roomId);
	}

	/**
	 */
	@Override
	public List<PersistedPurpose> getPersistedRoomPersistedPurposes(
		long roomId, int start, int end) {

		return persistedPurposePersistence.getPersistedRoomPersistedPurposes(
			roomId, start, end);
	}

	/**
	 */
	@Override
	public List<PersistedPurpose> getPersistedRoomPersistedPurposes(
		long roomId, int start, int end,
		OrderByComparator<PersistedPurpose> orderByComparator) {

		return persistedPurposePersistence.getPersistedRoomPersistedPurposes(
			roomId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getPersistedRoomPersistedPurposesCount(long roomId) {
		return persistedRoomPersistence.getPersistedPurposesSize(roomId);
	}

	/**
	 */
	@Override
	public boolean hasPersistedRoomPersistedPurpose(
		long roomId, long purposeId) {

		return persistedRoomPersistence.containsPersistedPurpose(
			roomId, purposeId);
	}

	/**
	 */
	@Override
	public boolean hasPersistedRoomPersistedPurposes(long roomId) {
		return persistedRoomPersistence.containsPersistedPurposes(roomId);
	}

	/**
	 */
	@Override
	public void setPersistedRoomPersistedPurposes(
		long roomId, long[] purposeIds) {

		persistedRoomPersistence.setPersistedPurposes(roomId, purposeIds);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			PersistedPurposeLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		persistedPurposeLocalService = (PersistedPurposeLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return PersistedPurposeLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return PersistedPurpose.class;
	}

	protected String getModelClassName() {
		return PersistedPurpose.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = persistedPurposePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected PersistedAmenityPersistence persistedAmenityPersistence;

	@Reference
	protected PersistedBookingPersistence persistedBookingPersistence;

	@Reference
	protected PersistedOfficePersistence persistedOfficePersistence;

	@Reference
	protected PersistedParticipantPersistence persistedParticipantPersistence;

	protected PersistedPurposeLocalService persistedPurposeLocalService;

	@Reference
	protected PersistedPurposePersistence persistedPurposePersistence;

	@Reference
	protected PersistedRoomPersistence persistedRoomPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.PortletPreferencesLocalService
		portletPreferencesLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}