/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jp.co.liferay.reservation.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import jp.co.liferay.reservation.model.PersistedRoom;
import jp.co.liferay.reservation.service.PersistedRoomLocalService;
import jp.co.liferay.reservation.service.persistence.PersistedAmenityPersistence;
import jp.co.liferay.reservation.service.persistence.PersistedBookingPersistence;
import jp.co.liferay.reservation.service.persistence.PersistedOfficePersistence;
import jp.co.liferay.reservation.service.persistence.PersistedParticipantPersistence;
import jp.co.liferay.reservation.service.persistence.PersistedPurposePersistence;
import jp.co.liferay.reservation.service.persistence.PersistedRoomPersistence;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the persisted room local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link jp.co.liferay.reservation.service.impl.PersistedRoomLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see jp.co.liferay.reservation.service.impl.PersistedRoomLocalServiceImpl
 * @generated
 */
public abstract class PersistedRoomLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, PersistedRoomLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>PersistedRoomLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>jp.co.liferay.reservation.service.PersistedRoomLocalServiceUtil</code>.
	 */

	/**
	 * Adds the persisted room to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedRoomLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param persistedRoom the persisted room
	 * @return the persisted room that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PersistedRoom addPersistedRoom(PersistedRoom persistedRoom) {
		persistedRoom.setNew(true);

		return persistedRoomPersistence.update(persistedRoom);
	}

	/**
	 * Creates a new persisted room with the primary key. Does not add the persisted room to the database.
	 *
	 * @param roomId the primary key for the new persisted room
	 * @return the new persisted room
	 */
	@Override
	@Transactional(enabled = false)
	public PersistedRoom createPersistedRoom(long roomId) {
		return persistedRoomPersistence.create(roomId);
	}

	/**
	 * Deletes the persisted room with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedRoomLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param roomId the primary key of the persisted room
	 * @return the persisted room that was removed
	 * @throws PortalException if a persisted room with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PersistedRoom deletePersistedRoom(long roomId)
		throws PortalException {

		return persistedRoomPersistence.remove(roomId);
	}

	/**
	 * Deletes the persisted room from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedRoomLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param persistedRoom the persisted room
	 * @return the persisted room that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PersistedRoom deletePersistedRoom(PersistedRoom persistedRoom) {
		return persistedRoomPersistence.remove(persistedRoom);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			PersistedRoom.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return persistedRoomPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jp.co.liferay.reservation.model.impl.PersistedRoomModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return persistedRoomPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jp.co.liferay.reservation.model.impl.PersistedRoomModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return persistedRoomPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return persistedRoomPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return persistedRoomPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public PersistedRoom fetchPersistedRoom(long roomId) {
		return persistedRoomPersistence.fetchByPrimaryKey(roomId);
	}

	/**
	 * Returns the persisted room with the matching UUID and company.
	 *
	 * @param uuid the persisted room's UUID
	 * @param companyId the primary key of the company
	 * @return the matching persisted room, or <code>null</code> if a matching persisted room could not be found
	 */
	@Override
	public PersistedRoom fetchPersistedRoomByUuidAndCompanyId(
		String uuid, long companyId) {

		return persistedRoomPersistence.fetchByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns the persisted room with the matching external reference code and company.
	 *
	 * @param companyId the primary key of the company
	 * @param externalReferenceCode the persisted room's external reference code
	 * @return the matching persisted room, or <code>null</code> if a matching persisted room could not be found
	 */
	@Override
	public PersistedRoom fetchPersistedRoomByReferenceCode(
		long companyId, String externalReferenceCode) {

		return persistedRoomPersistence.fetchByC_ERC(
			companyId, externalReferenceCode);
	}

	/**
	 * Returns the persisted room with the primary key.
	 *
	 * @param roomId the primary key of the persisted room
	 * @return the persisted room
	 * @throws PortalException if a persisted room with the primary key could not be found
	 */
	@Override
	public PersistedRoom getPersistedRoom(long roomId) throws PortalException {
		return persistedRoomPersistence.findByPrimaryKey(roomId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(persistedRoomLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PersistedRoom.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("roomId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			persistedRoomLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(PersistedRoom.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("roomId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(persistedRoomLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PersistedRoom.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("roomId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<PersistedRoom>() {

				@Override
				public void performAction(PersistedRoom persistedRoom)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, persistedRoom);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(PersistedRoom.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return persistedRoomLocalService.deletePersistedRoom(
			(PersistedRoom)persistedModel);
	}

	public BasePersistence<PersistedRoom> getBasePersistence() {
		return persistedRoomPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return persistedRoomPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the persisted room with the matching UUID and company.
	 *
	 * @param uuid the persisted room's UUID
	 * @param companyId the primary key of the company
	 * @return the matching persisted room
	 * @throws PortalException if a matching persisted room could not be found
	 */
	@Override
	public PersistedRoom getPersistedRoomByUuidAndCompanyId(
			String uuid, long companyId)
		throws PortalException {

		return persistedRoomPersistence.findByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns a range of all the persisted rooms.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jp.co.liferay.reservation.model.impl.PersistedRoomModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of persisted rooms
	 * @param end the upper bound of the range of persisted rooms (not inclusive)
	 * @return the range of persisted rooms
	 */
	@Override
	public List<PersistedRoom> getPersistedRooms(int start, int end) {
		return persistedRoomPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of persisted rooms.
	 *
	 * @return the number of persisted rooms
	 */
	@Override
	public int getPersistedRoomsCount() {
		return persistedRoomPersistence.countAll();
	}

	/**
	 * Updates the persisted room in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedRoomLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param persistedRoom the persisted room
	 * @return the persisted room that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PersistedRoom updatePersistedRoom(PersistedRoom persistedRoom) {
		return persistedRoomPersistence.update(persistedRoom);
	}

	/**
	 */
	@Override
	public void addPersistedPurposePersistedRoom(long purposeId, long roomId) {
		persistedPurposePersistence.addPersistedRoom(purposeId, roomId);
	}

	/**
	 */
	@Override
	public void addPersistedPurposePersistedRoom(
		long purposeId, PersistedRoom persistedRoom) {

		persistedPurposePersistence.addPersistedRoom(purposeId, persistedRoom);
	}

	/**
	 */
	@Override
	public void addPersistedPurposePersistedRooms(
		long purposeId, long[] roomIds) {

		persistedPurposePersistence.addPersistedRooms(purposeId, roomIds);
	}

	/**
	 */
	@Override
	public void addPersistedPurposePersistedRooms(
		long purposeId, List<PersistedRoom> persistedRooms) {

		persistedPurposePersistence.addPersistedRooms(
			purposeId, persistedRooms);
	}

	/**
	 */
	@Override
	public void clearPersistedPurposePersistedRooms(long purposeId) {
		persistedPurposePersistence.clearPersistedRooms(purposeId);
	}

	/**
	 */
	@Override
	public void deletePersistedPurposePersistedRoom(
		long purposeId, long roomId) {

		persistedPurposePersistence.removePersistedRoom(purposeId, roomId);
	}

	/**
	 */
	@Override
	public void deletePersistedPurposePersistedRoom(
		long purposeId, PersistedRoom persistedRoom) {

		persistedPurposePersistence.removePersistedRoom(
			purposeId, persistedRoom);
	}

	/**
	 */
	@Override
	public void deletePersistedPurposePersistedRooms(
		long purposeId, long[] roomIds) {

		persistedPurposePersistence.removePersistedRooms(purposeId, roomIds);
	}

	/**
	 */
	@Override
	public void deletePersistedPurposePersistedRooms(
		long purposeId, List<PersistedRoom> persistedRooms) {

		persistedPurposePersistence.removePersistedRooms(
			purposeId, persistedRooms);
	}

	/**
	 * Returns the purposeIds of the persisted purposes associated with the persisted room.
	 *
	 * @param roomId the roomId of the persisted room
	 * @return long[] the purposeIds of persisted purposes associated with the persisted room
	 */
	@Override
	public long[] getPersistedPurposePrimaryKeys(long roomId) {
		return persistedRoomPersistence.getPersistedPurposePrimaryKeys(roomId);
	}

	/**
	 */
	@Override
	public List<PersistedRoom> getPersistedPurposePersistedRooms(
		long purposeId) {

		return persistedRoomPersistence.getPersistedPurposePersistedRooms(
			purposeId);
	}

	/**
	 */
	@Override
	public List<PersistedRoom> getPersistedPurposePersistedRooms(
		long purposeId, int start, int end) {

		return persistedRoomPersistence.getPersistedPurposePersistedRooms(
			purposeId, start, end);
	}

	/**
	 */
	@Override
	public List<PersistedRoom> getPersistedPurposePersistedRooms(
		long purposeId, int start, int end,
		OrderByComparator<PersistedRoom> orderByComparator) {

		return persistedRoomPersistence.getPersistedPurposePersistedRooms(
			purposeId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getPersistedPurposePersistedRoomsCount(long purposeId) {
		return persistedPurposePersistence.getPersistedRoomsSize(purposeId);
	}

	/**
	 */
	@Override
	public boolean hasPersistedPurposePersistedRoom(
		long purposeId, long roomId) {

		return persistedPurposePersistence.containsPersistedRoom(
			purposeId, roomId);
	}

	/**
	 */
	@Override
	public boolean hasPersistedPurposePersistedRooms(long purposeId) {
		return persistedPurposePersistence.containsPersistedRooms(purposeId);
	}

	/**
	 */
	@Override
	public void setPersistedPurposePersistedRooms(
		long purposeId, long[] roomIds) {

		persistedPurposePersistence.setPersistedRooms(purposeId, roomIds);
	}

	/**
	 */
	@Override
	public void addPersistedAmenityPersistedRoom(long amenityId, long roomId) {
		persistedAmenityPersistence.addPersistedRoom(amenityId, roomId);
	}

	/**
	 */
	@Override
	public void addPersistedAmenityPersistedRoom(
		long amenityId, PersistedRoom persistedRoom) {

		persistedAmenityPersistence.addPersistedRoom(amenityId, persistedRoom);
	}

	/**
	 */
	@Override
	public void addPersistedAmenityPersistedRooms(
		long amenityId, long[] roomIds) {

		persistedAmenityPersistence.addPersistedRooms(amenityId, roomIds);
	}

	/**
	 */
	@Override
	public void addPersistedAmenityPersistedRooms(
		long amenityId, List<PersistedRoom> persistedRooms) {

		persistedAmenityPersistence.addPersistedRooms(
			amenityId, persistedRooms);
	}

	/**
	 */
	@Override
	public void clearPersistedAmenityPersistedRooms(long amenityId) {
		persistedAmenityPersistence.clearPersistedRooms(amenityId);
	}

	/**
	 */
	@Override
	public void deletePersistedAmenityPersistedRoom(
		long amenityId, long roomId) {

		persistedAmenityPersistence.removePersistedRoom(amenityId, roomId);
	}

	/**
	 */
	@Override
	public void deletePersistedAmenityPersistedRoom(
		long amenityId, PersistedRoom persistedRoom) {

		persistedAmenityPersistence.removePersistedRoom(
			amenityId, persistedRoom);
	}

	/**
	 */
	@Override
	public void deletePersistedAmenityPersistedRooms(
		long amenityId, long[] roomIds) {

		persistedAmenityPersistence.removePersistedRooms(amenityId, roomIds);
	}

	/**
	 */
	@Override
	public void deletePersistedAmenityPersistedRooms(
		long amenityId, List<PersistedRoom> persistedRooms) {

		persistedAmenityPersistence.removePersistedRooms(
			amenityId, persistedRooms);
	}

	/**
	 * Returns the amenityIds of the persisted amenities associated with the persisted room.
	 *
	 * @param roomId the roomId of the persisted room
	 * @return long[] the amenityIds of persisted amenities associated with the persisted room
	 */
	@Override
	public long[] getPersistedAmenityPrimaryKeys(long roomId) {
		return persistedRoomPersistence.getPersistedAmenityPrimaryKeys(roomId);
	}

	/**
	 */
	@Override
	public List<PersistedRoom> getPersistedAmenityPersistedRooms(
		long amenityId) {

		return persistedRoomPersistence.getPersistedAmenityPersistedRooms(
			amenityId);
	}

	/**
	 */
	@Override
	public List<PersistedRoom> getPersistedAmenityPersistedRooms(
		long amenityId, int start, int end) {

		return persistedRoomPersistence.getPersistedAmenityPersistedRooms(
			amenityId, start, end);
	}

	/**
	 */
	@Override
	public List<PersistedRoom> getPersistedAmenityPersistedRooms(
		long amenityId, int start, int end,
		OrderByComparator<PersistedRoom> orderByComparator) {

		return persistedRoomPersistence.getPersistedAmenityPersistedRooms(
			amenityId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getPersistedAmenityPersistedRoomsCount(long amenityId) {
		return persistedAmenityPersistence.getPersistedRoomsSize(amenityId);
	}

	/**
	 */
	@Override
	public boolean hasPersistedAmenityPersistedRoom(
		long amenityId, long roomId) {

		return persistedAmenityPersistence.containsPersistedRoom(
			amenityId, roomId);
	}

	/**
	 */
	@Override
	public boolean hasPersistedAmenityPersistedRooms(long amenityId) {
		return persistedAmenityPersistence.containsPersistedRooms(amenityId);
	}

	/**
	 */
	@Override
	public void setPersistedAmenityPersistedRooms(
		long amenityId, long[] roomIds) {

		persistedAmenityPersistence.setPersistedRooms(amenityId, roomIds);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			PersistedRoomLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		persistedRoomLocalService = (PersistedRoomLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return PersistedRoomLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return PersistedRoom.class;
	}

	protected String getModelClassName() {
		return PersistedRoom.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = persistedRoomPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected PersistedAmenityPersistence persistedAmenityPersistence;

	@Reference
	protected PersistedBookingPersistence persistedBookingPersistence;

	@Reference
	protected PersistedOfficePersistence persistedOfficePersistence;

	@Reference
	protected PersistedParticipantPersistence persistedParticipantPersistence;

	@Reference
	protected PersistedPurposePersistence persistedPurposePersistence;

	protected PersistedRoomLocalService persistedRoomLocalService;

	@Reference
	protected PersistedRoomPersistence persistedRoomPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.PortletPreferencesLocalService
		portletPreferencesLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}