/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jp.co.liferay.reservation.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import jp.co.liferay.reservation.model.PersistedOffice;
import jp.co.liferay.reservation.service.PersistedOfficeLocalService;
import jp.co.liferay.reservation.service.persistence.PersistedAmenityPersistence;
import jp.co.liferay.reservation.service.persistence.PersistedBookingPersistence;
import jp.co.liferay.reservation.service.persistence.PersistedOfficePersistence;
import jp.co.liferay.reservation.service.persistence.PersistedParticipantPersistence;
import jp.co.liferay.reservation.service.persistence.PersistedPurposePersistence;
import jp.co.liferay.reservation.service.persistence.PersistedRoomPersistence;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the persisted office local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link jp.co.liferay.reservation.service.impl.PersistedOfficeLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see jp.co.liferay.reservation.service.impl.PersistedOfficeLocalServiceImpl
 * @generated
 */
public abstract class PersistedOfficeLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   PersistedOfficeLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>PersistedOfficeLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>jp.co.liferay.reservation.service.PersistedOfficeLocalServiceUtil</code>.
	 */

	/**
	 * Adds the persisted office to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedOfficeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param persistedOffice the persisted office
	 * @return the persisted office that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PersistedOffice addPersistedOffice(PersistedOffice persistedOffice) {
		persistedOffice.setNew(true);

		return persistedOfficePersistence.update(persistedOffice);
	}

	/**
	 * Creates a new persisted office with the primary key. Does not add the persisted office to the database.
	 *
	 * @param officeId the primary key for the new persisted office
	 * @return the new persisted office
	 */
	@Override
	@Transactional(enabled = false)
	public PersistedOffice createPersistedOffice(long officeId) {
		return persistedOfficePersistence.create(officeId);
	}

	/**
	 * Deletes the persisted office with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedOfficeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param officeId the primary key of the persisted office
	 * @return the persisted office that was removed
	 * @throws PortalException if a persisted office with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PersistedOffice deletePersistedOffice(long officeId)
		throws PortalException {

		return persistedOfficePersistence.remove(officeId);
	}

	/**
	 * Deletes the persisted office from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedOfficeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param persistedOffice the persisted office
	 * @return the persisted office that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PersistedOffice deletePersistedOffice(
		PersistedOffice persistedOffice) {

		return persistedOfficePersistence.remove(persistedOffice);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			PersistedOffice.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return persistedOfficePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jp.co.liferay.reservation.model.impl.PersistedOfficeModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return persistedOfficePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jp.co.liferay.reservation.model.impl.PersistedOfficeModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return persistedOfficePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return persistedOfficePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return persistedOfficePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public PersistedOffice fetchPersistedOffice(long officeId) {
		return persistedOfficePersistence.fetchByPrimaryKey(officeId);
	}

	/**
	 * Returns the persisted office with the matching UUID and company.
	 *
	 * @param uuid the persisted office's UUID
	 * @param companyId the primary key of the company
	 * @return the matching persisted office, or <code>null</code> if a matching persisted office could not be found
	 */
	@Override
	public PersistedOffice fetchPersistedOfficeByUuidAndCompanyId(
		String uuid, long companyId) {

		return persistedOfficePersistence.fetchByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns the persisted office with the matching external reference code and company.
	 *
	 * @param companyId the primary key of the company
	 * @param externalReferenceCode the persisted office's external reference code
	 * @return the matching persisted office, or <code>null</code> if a matching persisted office could not be found
	 */
	@Override
	public PersistedOffice fetchPersistedOfficeByReferenceCode(
		long companyId, String externalReferenceCode) {

		return persistedOfficePersistence.fetchByC_ERC(
			companyId, externalReferenceCode);
	}

	/**
	 * Returns the persisted office with the primary key.
	 *
	 * @param officeId the primary key of the persisted office
	 * @return the persisted office
	 * @throws PortalException if a persisted office with the primary key could not be found
	 */
	@Override
	public PersistedOffice getPersistedOffice(long officeId)
		throws PortalException {

		return persistedOfficePersistence.findByPrimaryKey(officeId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(persistedOfficeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PersistedOffice.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("officeId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			persistedOfficeLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(PersistedOffice.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("officeId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(persistedOfficeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PersistedOffice.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("officeId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<PersistedOffice>() {

				@Override
				public void performAction(PersistedOffice persistedOffice)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, persistedOffice);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(PersistedOffice.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return persistedOfficeLocalService.deletePersistedOffice(
			(PersistedOffice)persistedModel);
	}

	public BasePersistence<PersistedOffice> getBasePersistence() {
		return persistedOfficePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return persistedOfficePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the persisted office with the matching UUID and company.
	 *
	 * @param uuid the persisted office's UUID
	 * @param companyId the primary key of the company
	 * @return the matching persisted office
	 * @throws PortalException if a matching persisted office could not be found
	 */
	@Override
	public PersistedOffice getPersistedOfficeByUuidAndCompanyId(
			String uuid, long companyId)
		throws PortalException {

		return persistedOfficePersistence.findByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns a range of all the persisted offices.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jp.co.liferay.reservation.model.impl.PersistedOfficeModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of persisted offices
	 * @param end the upper bound of the range of persisted offices (not inclusive)
	 * @return the range of persisted offices
	 */
	@Override
	public List<PersistedOffice> getPersistedOffices(int start, int end) {
		return persistedOfficePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of persisted offices.
	 *
	 * @return the number of persisted offices
	 */
	@Override
	public int getPersistedOfficesCount() {
		return persistedOfficePersistence.countAll();
	}

	/**
	 * Updates the persisted office in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedOfficeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param persistedOffice the persisted office
	 * @return the persisted office that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PersistedOffice updatePersistedOffice(
		PersistedOffice persistedOffice) {

		return persistedOfficePersistence.update(persistedOffice);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			PersistedOfficeLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		persistedOfficeLocalService = (PersistedOfficeLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return PersistedOfficeLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return PersistedOffice.class;
	}

	protected String getModelClassName() {
		return PersistedOffice.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = persistedOfficePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected PersistedAmenityPersistence persistedAmenityPersistence;

	@Reference
	protected PersistedBookingPersistence persistedBookingPersistence;

	protected PersistedOfficeLocalService persistedOfficeLocalService;

	@Reference
	protected PersistedOfficePersistence persistedOfficePersistence;

	@Reference
	protected PersistedParticipantPersistence persistedParticipantPersistence;

	@Reference
	protected PersistedPurposePersistence persistedPurposePersistence;

	@Reference
	protected PersistedRoomPersistence persistedRoomPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.PortletPreferencesLocalService
		portletPreferencesLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}