/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jp.co.liferay.reservation.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import jp.co.liferay.reservation.model.PersistedAmenity;
import jp.co.liferay.reservation.service.PersistedAmenityLocalService;
import jp.co.liferay.reservation.service.persistence.PersistedAmenityPersistence;
import jp.co.liferay.reservation.service.persistence.PersistedBookingPersistence;
import jp.co.liferay.reservation.service.persistence.PersistedOfficePersistence;
import jp.co.liferay.reservation.service.persistence.PersistedParticipantPersistence;
import jp.co.liferay.reservation.service.persistence.PersistedPurposePersistence;
import jp.co.liferay.reservation.service.persistence.PersistedRoomPersistence;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the persisted amenity local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link jp.co.liferay.reservation.service.impl.PersistedAmenityLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see jp.co.liferay.reservation.service.impl.PersistedAmenityLocalServiceImpl
 * @generated
 */
public abstract class PersistedAmenityLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   PersistedAmenityLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>PersistedAmenityLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>jp.co.liferay.reservation.service.PersistedAmenityLocalServiceUtil</code>.
	 */

	/**
	 * Adds the persisted amenity to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedAmenityLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param persistedAmenity the persisted amenity
	 * @return the persisted amenity that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PersistedAmenity addPersistedAmenity(
		PersistedAmenity persistedAmenity) {

		persistedAmenity.setNew(true);

		return persistedAmenityPersistence.update(persistedAmenity);
	}

	/**
	 * Creates a new persisted amenity with the primary key. Does not add the persisted amenity to the database.
	 *
	 * @param amenityId the primary key for the new persisted amenity
	 * @return the new persisted amenity
	 */
	@Override
	@Transactional(enabled = false)
	public PersistedAmenity createPersistedAmenity(long amenityId) {
		return persistedAmenityPersistence.create(amenityId);
	}

	/**
	 * Deletes the persisted amenity with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedAmenityLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param amenityId the primary key of the persisted amenity
	 * @return the persisted amenity that was removed
	 * @throws PortalException if a persisted amenity with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PersistedAmenity deletePersistedAmenity(long amenityId)
		throws PortalException {

		return persistedAmenityPersistence.remove(amenityId);
	}

	/**
	 * Deletes the persisted amenity from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedAmenityLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param persistedAmenity the persisted amenity
	 * @return the persisted amenity that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PersistedAmenity deletePersistedAmenity(
		PersistedAmenity persistedAmenity) {

		return persistedAmenityPersistence.remove(persistedAmenity);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			PersistedAmenity.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return persistedAmenityPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jp.co.liferay.reservation.model.impl.PersistedAmenityModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return persistedAmenityPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jp.co.liferay.reservation.model.impl.PersistedAmenityModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return persistedAmenityPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return persistedAmenityPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return persistedAmenityPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public PersistedAmenity fetchPersistedAmenity(long amenityId) {
		return persistedAmenityPersistence.fetchByPrimaryKey(amenityId);
	}

	/**
	 * Returns the persisted amenity with the matching UUID and company.
	 *
	 * @param uuid the persisted amenity's UUID
	 * @param companyId the primary key of the company
	 * @return the matching persisted amenity, or <code>null</code> if a matching persisted amenity could not be found
	 */
	@Override
	public PersistedAmenity fetchPersistedAmenityByUuidAndCompanyId(
		String uuid, long companyId) {

		return persistedAmenityPersistence.fetchByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns the persisted amenity with the matching external reference code and company.
	 *
	 * @param companyId the primary key of the company
	 * @param externalReferenceCode the persisted amenity's external reference code
	 * @return the matching persisted amenity, or <code>null</code> if a matching persisted amenity could not be found
	 */
	@Override
	public PersistedAmenity fetchPersistedAmenityByReferenceCode(
		long companyId, String externalReferenceCode) {

		return persistedAmenityPersistence.fetchByC_ERC(
			companyId, externalReferenceCode);
	}

	/**
	 * Returns the persisted amenity with the primary key.
	 *
	 * @param amenityId the primary key of the persisted amenity
	 * @return the persisted amenity
	 * @throws PortalException if a persisted amenity with the primary key could not be found
	 */
	@Override
	public PersistedAmenity getPersistedAmenity(long amenityId)
		throws PortalException {

		return persistedAmenityPersistence.findByPrimaryKey(amenityId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			persistedAmenityLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PersistedAmenity.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("amenityId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			persistedAmenityLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(PersistedAmenity.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("amenityId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			persistedAmenityLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PersistedAmenity.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("amenityId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return persistedAmenityLocalService.deletePersistedAmenity(
			(PersistedAmenity)persistedModel);
	}

	public BasePersistence<PersistedAmenity> getBasePersistence() {
		return persistedAmenityPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return persistedAmenityPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the persisted amenity with the matching UUID and company.
	 *
	 * @param uuid the persisted amenity's UUID
	 * @param companyId the primary key of the company
	 * @return the matching persisted amenity
	 * @throws PortalException if a matching persisted amenity could not be found
	 */
	@Override
	public PersistedAmenity getPersistedAmenityByUuidAndCompanyId(
			String uuid, long companyId)
		throws PortalException {

		return persistedAmenityPersistence.findByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns a range of all the persisted amenities.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>jp.co.liferay.reservation.model.impl.PersistedAmenityModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of persisted amenities
	 * @param end the upper bound of the range of persisted amenities (not inclusive)
	 * @return the range of persisted amenities
	 */
	@Override
	public List<PersistedAmenity> getPersistedAmenities(int start, int end) {
		return persistedAmenityPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of persisted amenities.
	 *
	 * @return the number of persisted amenities
	 */
	@Override
	public int getPersistedAmenitiesCount() {
		return persistedAmenityPersistence.countAll();
	}

	/**
	 * Updates the persisted amenity in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PersistedAmenityLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param persistedAmenity the persisted amenity
	 * @return the persisted amenity that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PersistedAmenity updatePersistedAmenity(
		PersistedAmenity persistedAmenity) {

		return persistedAmenityPersistence.update(persistedAmenity);
	}

	/**
	 */
	@Override
	public void addPersistedRoomPersistedAmenity(long roomId, long amenityId) {
		persistedRoomPersistence.addPersistedAmenity(roomId, amenityId);
	}

	/**
	 */
	@Override
	public void addPersistedRoomPersistedAmenity(
		long roomId, PersistedAmenity persistedAmenity) {

		persistedRoomPersistence.addPersistedAmenity(roomId, persistedAmenity);
	}

	/**
	 */
	@Override
	public void addPersistedRoomPersistedAmenities(
		long roomId, long[] amenityIds) {

		persistedRoomPersistence.addPersistedAmenities(roomId, amenityIds);
	}

	/**
	 */
	@Override
	public void addPersistedRoomPersistedAmenities(
		long roomId, List<PersistedAmenity> persistedAmenities) {

		persistedRoomPersistence.addPersistedAmenities(
			roomId, persistedAmenities);
	}

	/**
	 */
	@Override
	public void clearPersistedRoomPersistedAmenities(long roomId) {
		persistedRoomPersistence.clearPersistedAmenities(roomId);
	}

	/**
	 */
	@Override
	public void deletePersistedRoomPersistedAmenity(
		long roomId, long amenityId) {

		persistedRoomPersistence.removePersistedAmenity(roomId, amenityId);
	}

	/**
	 */
	@Override
	public void deletePersistedRoomPersistedAmenity(
		long roomId, PersistedAmenity persistedAmenity) {

		persistedRoomPersistence.removePersistedAmenity(
			roomId, persistedAmenity);
	}

	/**
	 */
	@Override
	public void deletePersistedRoomPersistedAmenities(
		long roomId, long[] amenityIds) {

		persistedRoomPersistence.removePersistedAmenities(roomId, amenityIds);
	}

	/**
	 */
	@Override
	public void deletePersistedRoomPersistedAmenities(
		long roomId, List<PersistedAmenity> persistedAmenities) {

		persistedRoomPersistence.removePersistedAmenities(
			roomId, persistedAmenities);
	}

	/**
	 * Returns the roomIds of the persisted rooms associated with the persisted amenity.
	 *
	 * @param amenityId the amenityId of the persisted amenity
	 * @return long[] the roomIds of persisted rooms associated with the persisted amenity
	 */
	@Override
	public long[] getPersistedRoomPrimaryKeys(long amenityId) {
		return persistedAmenityPersistence.getPersistedRoomPrimaryKeys(
			amenityId);
	}

	/**
	 */
	@Override
	public List<PersistedAmenity> getPersistedRoomPersistedAmenities(
		long roomId) {

		return persistedAmenityPersistence.getPersistedRoomPersistedAmenities(
			roomId);
	}

	/**
	 */
	@Override
	public List<PersistedAmenity> getPersistedRoomPersistedAmenities(
		long roomId, int start, int end) {

		return persistedAmenityPersistence.getPersistedRoomPersistedAmenities(
			roomId, start, end);
	}

	/**
	 */
	@Override
	public List<PersistedAmenity> getPersistedRoomPersistedAmenities(
		long roomId, int start, int end,
		OrderByComparator<PersistedAmenity> orderByComparator) {

		return persistedAmenityPersistence.getPersistedRoomPersistedAmenities(
			roomId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getPersistedRoomPersistedAmenitiesCount(long roomId) {
		return persistedRoomPersistence.getPersistedAmenitiesSize(roomId);
	}

	/**
	 */
	@Override
	public boolean hasPersistedRoomPersistedAmenity(
		long roomId, long amenityId) {

		return persistedRoomPersistence.containsPersistedAmenity(
			roomId, amenityId);
	}

	/**
	 */
	@Override
	public boolean hasPersistedRoomPersistedAmenities(long roomId) {
		return persistedRoomPersistence.containsPersistedAmenities(roomId);
	}

	/**
	 */
	@Override
	public void setPersistedRoomPersistedAmenities(
		long roomId, long[] amenityIds) {

		persistedRoomPersistence.setPersistedAmenities(roomId, amenityIds);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			PersistedAmenityLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		persistedAmenityLocalService = (PersistedAmenityLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return PersistedAmenityLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return PersistedAmenity.class;
	}

	protected String getModelClassName() {
		return PersistedAmenity.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = persistedAmenityPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected PersistedAmenityLocalService persistedAmenityLocalService;

	@Reference
	protected PersistedAmenityPersistence persistedAmenityPersistence;

	@Reference
	protected PersistedBookingPersistence persistedBookingPersistence;

	@Reference
	protected PersistedOfficePersistence persistedOfficePersistence;

	@Reference
	protected PersistedParticipantPersistence persistedParticipantPersistence;

	@Reference
	protected PersistedPurposePersistence persistedPurposePersistence;

	@Reference
	protected PersistedRoomPersistence persistedRoomPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.PortletPreferencesLocalService
		portletPreferencesLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}