/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jp.co.liferay.reservation.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PersistedBooking service. Represents a row in the &quot;Reservation_PersistedBooking&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>jp.co.liferay.reservation.model.impl.PersistedBookingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>jp.co.liferay.reservation.model.impl.PersistedBookingImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PersistedBooking
 * @generated
 */
@ProviderType
public interface PersistedBookingModel
	extends BaseModel<PersistedBooking>, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a persisted booking model instance should use the {@link PersistedBooking} interface instead.
	 */

	/**
	 * Returns the primary key of this persisted booking.
	 *
	 * @return the primary key of this persisted booking
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this persisted booking.
	 *
	 * @param primaryKey the primary key of this persisted booking
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this persisted booking.
	 *
	 * @return the uuid of this persisted booking
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this persisted booking.
	 *
	 * @param uuid the uuid of this persisted booking
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this persisted booking.
	 *
	 * @return the external reference code of this persisted booking
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this persisted booking.
	 *
	 * @param externalReferenceCode the external reference code of this persisted booking
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the booking ID of this persisted booking.
	 *
	 * @return the booking ID of this persisted booking
	 */
	public long getBookingId();

	/**
	 * Sets the booking ID of this persisted booking.
	 *
	 * @param bookingId the booking ID of this persisted booking
	 */
	public void setBookingId(long bookingId);

	/**
	 * Returns the calendar booking ID of this persisted booking.
	 *
	 * @return the calendar booking ID of this persisted booking
	 */
	public long getCalendarBookingId();

	/**
	 * Sets the calendar booking ID of this persisted booking.
	 *
	 * @param calendarBookingId the calendar booking ID of this persisted booking
	 */
	public void setCalendarBookingId(long calendarBookingId);

	/**
	 * Returns the title of this persisted booking.
	 *
	 * @return the title of this persisted booking
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this persisted booking.
	 *
	 * @param title the title of this persisted booking
	 */
	public void setTitle(String title);

	/**
	 * Returns the start date of this persisted booking.
	 *
	 * @return the start date of this persisted booking
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this persisted booking.
	 *
	 * @param startDate the start date of this persisted booking
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this persisted booking.
	 *
	 * @return the end date of this persisted booking
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this persisted booking.
	 *
	 * @param endDate the end date of this persisted booking
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the room ID of this persisted booking.
	 *
	 * @return the room ID of this persisted booking
	 */
	public long getRoomId();

	/**
	 * Sets the room ID of this persisted booking.
	 *
	 * @param roomId the room ID of this persisted booking
	 */
	public void setRoomId(long roomId);

	/**
	 * Returns the description of this persisted booking.
	 *
	 * @return the description of this persisted booking
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this persisted booking.
	 *
	 * @param description the description of this persisted booking
	 */
	public void setDescription(String description);

	/**
	 * Returns the company ID of this persisted booking.
	 *
	 * @return the company ID of this persisted booking
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this persisted booking.
	 *
	 * @param companyId the company ID of this persisted booking
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this persisted booking.
	 *
	 * @return the user ID of this persisted booking
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this persisted booking.
	 *
	 * @param userId the user ID of this persisted booking
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this persisted booking.
	 *
	 * @return the user uuid of this persisted booking
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this persisted booking.
	 *
	 * @param userUuid the user uuid of this persisted booking
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this persisted booking.
	 *
	 * @return the user name of this persisted booking
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this persisted booking.
	 *
	 * @param userName the user name of this persisted booking
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this persisted booking.
	 *
	 * @return the create date of this persisted booking
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this persisted booking.
	 *
	 * @param createDate the create date of this persisted booking
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this persisted booking.
	 *
	 * @return the modified date of this persisted booking
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this persisted booking.
	 *
	 * @param modifiedDate the modified date of this persisted booking
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}