/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jp.co.liferay.reservation.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PersistedRoom service. Represents a row in the &quot;Reservation_PersistedRoom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>jp.co.liferay.reservation.model.impl.PersistedRoomModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>jp.co.liferay.reservation.model.impl.PersistedRoomImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PersistedRoom
 * @generated
 */
@ProviderType
public interface PersistedRoomModel
	extends BaseModel<PersistedRoom>, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a persisted room model instance should use the {@link PersistedRoom} interface instead.
	 */

	/**
	 * Returns the primary key of this persisted room.
	 *
	 * @return the primary key of this persisted room
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this persisted room.
	 *
	 * @param primaryKey the primary key of this persisted room
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this persisted room.
	 *
	 * @return the uuid of this persisted room
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this persisted room.
	 *
	 * @param uuid the uuid of this persisted room
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this persisted room.
	 *
	 * @return the external reference code of this persisted room
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this persisted room.
	 *
	 * @param externalReferenceCode the external reference code of this persisted room
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the room ID of this persisted room.
	 *
	 * @return the room ID of this persisted room
	 */
	public long getRoomId();

	/**
	 * Sets the room ID of this persisted room.
	 *
	 * @param roomId the room ID of this persisted room
	 */
	public void setRoomId(long roomId);

	/**
	 * Returns the calendar ID of this persisted room.
	 *
	 * @return the calendar ID of this persisted room
	 */
	public long getCalendarId();

	/**
	 * Sets the calendar ID of this persisted room.
	 *
	 * @param calendarId the calendar ID of this persisted room
	 */
	public void setCalendarId(long calendarId);

	/**
	 * Returns the name of this persisted room.
	 *
	 * @return the name of this persisted room
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this persisted room.
	 *
	 * @param name the name of this persisted room
	 */
	public void setName(String name);

	/**
	 * Returns the photo path of this persisted room.
	 *
	 * @return the photo path of this persisted room
	 */
	@AutoEscape
	public String getPhotoPath();

	/**
	 * Sets the photo path of this persisted room.
	 *
	 * @param photoPath the photo path of this persisted room
	 */
	public void setPhotoPath(String photoPath);

	/**
	 * Returns the available monday of this persisted room.
	 *
	 * @return the available monday of this persisted room
	 */
	public boolean getAvailableMonday();

	/**
	 * Returns <code>true</code> if this persisted room is available monday.
	 *
	 * @return <code>true</code> if this persisted room is available monday; <code>false</code> otherwise
	 */
	public boolean isAvailableMonday();

	/**
	 * Sets whether this persisted room is available monday.
	 *
	 * @param availableMonday the available monday of this persisted room
	 */
	public void setAvailableMonday(boolean availableMonday);

	/**
	 * Returns the available tuesday of this persisted room.
	 *
	 * @return the available tuesday of this persisted room
	 */
	public boolean getAvailableTuesday();

	/**
	 * Returns <code>true</code> if this persisted room is available tuesday.
	 *
	 * @return <code>true</code> if this persisted room is available tuesday; <code>false</code> otherwise
	 */
	public boolean isAvailableTuesday();

	/**
	 * Sets whether this persisted room is available tuesday.
	 *
	 * @param availableTuesday the available tuesday of this persisted room
	 */
	public void setAvailableTuesday(boolean availableTuesday);

	/**
	 * Returns the available wednesday of this persisted room.
	 *
	 * @return the available wednesday of this persisted room
	 */
	public boolean getAvailableWednesday();

	/**
	 * Returns <code>true</code> if this persisted room is available wednesday.
	 *
	 * @return <code>true</code> if this persisted room is available wednesday; <code>false</code> otherwise
	 */
	public boolean isAvailableWednesday();

	/**
	 * Sets whether this persisted room is available wednesday.
	 *
	 * @param availableWednesday the available wednesday of this persisted room
	 */
	public void setAvailableWednesday(boolean availableWednesday);

	/**
	 * Returns the available thursday of this persisted room.
	 *
	 * @return the available thursday of this persisted room
	 */
	public boolean getAvailableThursday();

	/**
	 * Returns <code>true</code> if this persisted room is available thursday.
	 *
	 * @return <code>true</code> if this persisted room is available thursday; <code>false</code> otherwise
	 */
	public boolean isAvailableThursday();

	/**
	 * Sets whether this persisted room is available thursday.
	 *
	 * @param availableThursday the available thursday of this persisted room
	 */
	public void setAvailableThursday(boolean availableThursday);

	/**
	 * Returns the available friday of this persisted room.
	 *
	 * @return the available friday of this persisted room
	 */
	public boolean getAvailableFriday();

	/**
	 * Returns <code>true</code> if this persisted room is available friday.
	 *
	 * @return <code>true</code> if this persisted room is available friday; <code>false</code> otherwise
	 */
	public boolean isAvailableFriday();

	/**
	 * Sets whether this persisted room is available friday.
	 *
	 * @param availableFriday the available friday of this persisted room
	 */
	public void setAvailableFriday(boolean availableFriday);

	/**
	 * Returns the available saturday of this persisted room.
	 *
	 * @return the available saturday of this persisted room
	 */
	public boolean getAvailableSaturday();

	/**
	 * Returns <code>true</code> if this persisted room is available saturday.
	 *
	 * @return <code>true</code> if this persisted room is available saturday; <code>false</code> otherwise
	 */
	public boolean isAvailableSaturday();

	/**
	 * Sets whether this persisted room is available saturday.
	 *
	 * @param availableSaturday the available saturday of this persisted room
	 */
	public void setAvailableSaturday(boolean availableSaturday);

	/**
	 * Returns the available sunday of this persisted room.
	 *
	 * @return the available sunday of this persisted room
	 */
	public boolean getAvailableSunday();

	/**
	 * Returns <code>true</code> if this persisted room is available sunday.
	 *
	 * @return <code>true</code> if this persisted room is available sunday; <code>false</code> otherwise
	 */
	public boolean isAvailableSunday();

	/**
	 * Sets whether this persisted room is available sunday.
	 *
	 * @param availableSunday the available sunday of this persisted room
	 */
	public void setAvailableSunday(boolean availableSunday);

	/**
	 * Returns the available start time of this persisted room.
	 *
	 * @return the available start time of this persisted room
	 */
	public int getAvailableStartTime();

	/**
	 * Sets the available start time of this persisted room.
	 *
	 * @param availableStartTime the available start time of this persisted room
	 */
	public void setAvailableStartTime(int availableStartTime);

	/**
	 * Returns the available end time of this persisted room.
	 *
	 * @return the available end time of this persisted room
	 */
	public int getAvailableEndTime();

	/**
	 * Sets the available end time of this persisted room.
	 *
	 * @param availableEndTime the available end time of this persisted room
	 */
	public void setAvailableEndTime(int availableEndTime);

	/**
	 * Returns the office ID of this persisted room.
	 *
	 * @return the office ID of this persisted room
	 */
	public long getOfficeId();

	/**
	 * Sets the office ID of this persisted room.
	 *
	 * @param officeId the office ID of this persisted room
	 */
	public void setOfficeId(long officeId);

	/**
	 * Returns the capacity square meters of this persisted room.
	 *
	 * @return the capacity square meters of this persisted room
	 */
	public double getCapacitySquareMeters();

	/**
	 * Sets the capacity square meters of this persisted room.
	 *
	 * @param capacitySquareMeters the capacity square meters of this persisted room
	 */
	public void setCapacitySquareMeters(double capacitySquareMeters);

	/**
	 * Returns the capacity people of this persisted room.
	 *
	 * @return the capacity people of this persisted room
	 */
	public int getCapacityPeople();

	/**
	 * Sets the capacity people of this persisted room.
	 *
	 * @param capacityPeople the capacity people of this persisted room
	 */
	public void setCapacityPeople(int capacityPeople);

	/**
	 * Returns the phone extension of this persisted room.
	 *
	 * @return the phone extension of this persisted room
	 */
	public int getPhoneExtension();

	/**
	 * Sets the phone extension of this persisted room.
	 *
	 * @param phoneExtension the phone extension of this persisted room
	 */
	public void setPhoneExtension(int phoneExtension);

	/**
	 * Returns the wifi ssid of this persisted room.
	 *
	 * @return the wifi ssid of this persisted room
	 */
	@AutoEscape
	public String getWifiSSID();

	/**
	 * Sets the wifi ssid of this persisted room.
	 *
	 * @param wifiSSID the wifi ssid of this persisted room
	 */
	public void setWifiSSID(String wifiSSID);

	/**
	 * Returns the wifi security type of this persisted room.
	 *
	 * @return the wifi security type of this persisted room
	 */
	public int getWifiSecurityType();

	/**
	 * Sets the wifi security type of this persisted room.
	 *
	 * @param wifiSecurityType the wifi security type of this persisted room
	 */
	public void setWifiSecurityType(int wifiSecurityType);

	/**
	 * Returns the wifi password of this persisted room.
	 *
	 * @return the wifi password of this persisted room
	 */
	@AutoEscape
	public String getWifiPassword();

	/**
	 * Sets the wifi password of this persisted room.
	 *
	 * @param wifiPassword the wifi password of this persisted room
	 */
	public void setWifiPassword(String wifiPassword);

	/**
	 * Returns the company ID of this persisted room.
	 *
	 * @return the company ID of this persisted room
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this persisted room.
	 *
	 * @param companyId the company ID of this persisted room
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this persisted room.
	 *
	 * @return the user ID of this persisted room
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this persisted room.
	 *
	 * @param userId the user ID of this persisted room
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this persisted room.
	 *
	 * @return the user uuid of this persisted room
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this persisted room.
	 *
	 * @param userUuid the user uuid of this persisted room
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this persisted room.
	 *
	 * @return the user name of this persisted room
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this persisted room.
	 *
	 * @param userName the user name of this persisted room
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this persisted room.
	 *
	 * @return the create date of this persisted room
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this persisted room.
	 *
	 * @param createDate the create date of this persisted room
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this persisted room.
	 *
	 * @return the modified date of this persisted room
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this persisted room.
	 *
	 * @param modifiedDate the modified date of this persisted room
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

}