/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jp.co.liferay.reservation.model.impl;

import jp.co.liferay.reservation.model.PersistedOffice;
import jp.co.liferay.reservation.service.PersistedOfficeLocalServiceUtil;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The extended model base implementation for the PersistedOffice service. Represents a row in the &quot;Reservation_PersistedOffice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PersistedOfficeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PersistedOfficeImpl
 * @see PersistedOffice
 * @generated
 */
@ProviderType
public abstract class PersistedOfficeBaseImpl
	extends PersistedOfficeModelImpl implements PersistedOffice {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a persisted office model instance should use the <code>PersistedOffice</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			PersistedOfficeLocalServiceUtil.addPersistedOffice(this);
		}
		else {
			PersistedOfficeLocalServiceUtil.updatePersistedOffice(this);
		}
	}

}