/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jp.co.liferay.reservation.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import jp.co.liferay.reservation.model.PersistedAmenity;
import jp.co.liferay.reservation.model.PersistedAmenityModel;
import jp.co.liferay.reservation.model.PersistedAmenitySoap;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the PersistedAmenity service. Represents a row in the &quot;Reservation_PersistedAmenity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>PersistedAmenityModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PersistedAmenityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PersistedAmenityImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class PersistedAmenityModelImpl
	extends BaseModelImpl<PersistedAmenity> implements PersistedAmenityModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a persisted amenity model instance should use the <code>PersistedAmenity</code> interface instead.
	 */
	public static final String TABLE_NAME = "Reservation_PersistedAmenity";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"amenityId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"companyId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("amenityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Reservation_PersistedAmenity (uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,amenityId LONG not null primary key,name VARCHAR(75) null,companyId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table Reservation_PersistedAmenity";

	public static final String ORDER_BY_JPQL =
		" ORDER BY persistedAmenity.amenityId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Reservation_PersistedAmenity.amenityId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long AMENITYID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PersistedAmenity toModel(PersistedAmenitySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		PersistedAmenity model = new PersistedAmenityImpl();

		model.setUuid(soapModel.getUuid());
		model.setExternalReferenceCode(soapModel.getExternalReferenceCode());
		model.setAmenityId(soapModel.getAmenityId());
		model.setName(soapModel.getName());
		model.setCompanyId(soapModel.getCompanyId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PersistedAmenity> toModels(
		PersistedAmenitySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<PersistedAmenity> models = new ArrayList<PersistedAmenity>(
			soapModels.length);

		for (PersistedAmenitySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final String MAPPING_TABLE_RESERVATION_ROOMS_AMENITIES_NAME =
		"Reservation_Rooms_Amenities";

	public static final Object[][]
		MAPPING_TABLE_RESERVATION_ROOMS_AMENITIES_COLUMNS = {
			{"companyId", Types.BIGINT}, {"amenityId", Types.BIGINT},
			{"roomId", Types.BIGINT}
		};

	public static final String
		MAPPING_TABLE_RESERVATION_ROOMS_AMENITIES_SQL_CREATE =
			"create table Reservation_Rooms_Amenities (companyId LONG not null,amenityId LONG not null,roomId LONG not null,primary key (amenityId, roomId))";

	public PersistedAmenityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _amenityId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAmenityId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _amenityId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PersistedAmenity.class;
	}

	@Override
	public String getModelClassName() {
		return PersistedAmenity.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PersistedAmenity, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PersistedAmenity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PersistedAmenity, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PersistedAmenity)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PersistedAmenity, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PersistedAmenity, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PersistedAmenity)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PersistedAmenity, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PersistedAmenity, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, PersistedAmenity>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			PersistedAmenity.class.getClassLoader(), PersistedAmenity.class,
			ModelWrapper.class);

		try {
			Constructor<PersistedAmenity> constructor =
				(Constructor<PersistedAmenity>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<PersistedAmenity, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PersistedAmenity, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PersistedAmenity, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<PersistedAmenity, Object>>();
		Map<String, BiConsumer<PersistedAmenity, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<PersistedAmenity, ?>>();

		attributeGetterFunctions.put("uuid", PersistedAmenity::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<PersistedAmenity, String>)PersistedAmenity::setUuid);
		attributeGetterFunctions.put(
			"externalReferenceCode",
			PersistedAmenity::getExternalReferenceCode);
		attributeSetterBiConsumers.put(
			"externalReferenceCode",
			(BiConsumer<PersistedAmenity, String>)
				PersistedAmenity::setExternalReferenceCode);
		attributeGetterFunctions.put(
			"amenityId", PersistedAmenity::getAmenityId);
		attributeSetterBiConsumers.put(
			"amenityId",
			(BiConsumer<PersistedAmenity, Long>)PersistedAmenity::setAmenityId);
		attributeGetterFunctions.put("name", PersistedAmenity::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<PersistedAmenity, String>)PersistedAmenity::setName);
		attributeGetterFunctions.put(
			"companyId", PersistedAmenity::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<PersistedAmenity, Long>)PersistedAmenity::setCompanyId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		_columnBitmask |= EXTERNALREFERENCECODE_COLUMN_BITMASK;

		if (_originalExternalReferenceCode == null) {
			_originalExternalReferenceCode = _externalReferenceCode;
		}

		_externalReferenceCode = externalReferenceCode;
	}

	public String getOriginalExternalReferenceCode() {
		return GetterUtil.getString(_originalExternalReferenceCode);
	}

	@JSON
	@Override
	public long getAmenityId() {
		return _amenityId;
	}

	@Override
	public void setAmenityId(long amenityId) {
		_amenityId = amenityId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PersistedAmenity.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PersistedAmenity toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PersistedAmenity>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PersistedAmenityImpl persistedAmenityImpl = new PersistedAmenityImpl();

		persistedAmenityImpl.setUuid(getUuid());
		persistedAmenityImpl.setExternalReferenceCode(
			getExternalReferenceCode());
		persistedAmenityImpl.setAmenityId(getAmenityId());
		persistedAmenityImpl.setName(getName());
		persistedAmenityImpl.setCompanyId(getCompanyId());

		persistedAmenityImpl.resetOriginalValues();

		return persistedAmenityImpl;
	}

	@Override
	public int compareTo(PersistedAmenity persistedAmenity) {
		long primaryKey = persistedAmenity.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PersistedAmenity)) {
			return false;
		}

		PersistedAmenity persistedAmenity = (PersistedAmenity)obj;

		long primaryKey = persistedAmenity.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		PersistedAmenityModelImpl persistedAmenityModelImpl = this;

		persistedAmenityModelImpl._originalUuid =
			persistedAmenityModelImpl._uuid;

		persistedAmenityModelImpl._originalExternalReferenceCode =
			persistedAmenityModelImpl._externalReferenceCode;

		persistedAmenityModelImpl._originalCompanyId =
			persistedAmenityModelImpl._companyId;

		persistedAmenityModelImpl._setOriginalCompanyId = false;

		persistedAmenityModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PersistedAmenity> toCacheModel() {
		PersistedAmenityCacheModel persistedAmenityCacheModel =
			new PersistedAmenityCacheModel();

		persistedAmenityCacheModel.uuid = getUuid();

		String uuid = persistedAmenityCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			persistedAmenityCacheModel.uuid = null;
		}

		persistedAmenityCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			persistedAmenityCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			persistedAmenityCacheModel.externalReferenceCode = null;
		}

		persistedAmenityCacheModel.amenityId = getAmenityId();

		persistedAmenityCacheModel.name = getName();

		String name = persistedAmenityCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			persistedAmenityCacheModel.name = null;
		}

		persistedAmenityCacheModel.companyId = getCompanyId();

		return persistedAmenityCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PersistedAmenity, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PersistedAmenity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PersistedAmenity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((PersistedAmenity)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PersistedAmenity, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PersistedAmenity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PersistedAmenity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((PersistedAmenity)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PersistedAmenity>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private String _externalReferenceCode;
	private String _originalExternalReferenceCode;
	private long _amenityId;
	private String _name;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _columnBitmask;
	private PersistedAmenity _escapedModel;

}